=== juliagromna/XML/XML/tv_programDTD.dtd
<!ELEMENT tvprogram (program+)>
<!ATTLIST program type (movie|tv-series|animation) #REQUIRED>
<!ELEMENT program (title,director,poster,streaming-time)>
<!ATTLIST title year CDATA #REQUIRED
                age CDATA "12+"
                episode CDATA #IMPLIED>
<!ATTLIST streaming-time date CDATA "13-03-2023"
                        length CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)*>
<!ELEMENT director (#PCDATA)*>
<!ELEMENT poster (#PCDATA)*>
<!ELEMENT streaming-time (#PCDATA)*>

=== juliagromna/XML/XML/tv_program.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="tv_program.xslt"?>

<!DOCTYPE tvprogram SYSTEM "tv_programDTD.dtd">

<tvprogram>
    <program type="animation">
        <title year="2001" age="8+">Atlantis: The Lost Empire</title>
        <director>Kirk Wise, Gary Trousdale</director>
        <poster>https://m.media-amazon.com/images/I/51+oXbQRqDL._AC_UF894,1000_QL80_.jpg</poster>
        <streaming-time date="13-03-2023" length="1h 35m">15:15-17:00</streaming-time>
    </program>
    <program type="tv-series">
        <title year="2018" episode="s14e07" age="16+">Supernatural</title>
        <director>Eric Kripke</director>
        <poster>https://ae01.alicdn.com/kf/HTB1P4HDbEWF3KVjSZPhq6xclXXaF/Q2719-plakaty-i-druki-Supernatural-Season14-12x18-24x36-Sam-Dean-Winchester-Castiel-plakat-artystyczny-na-p.jpg_Q90.jpg_.webp</poster>
        <streaming-time date="13-03-2023" length="41m">17:00-17:45</streaming-time>
    </program>
    <program type="tv-series">
        <title year="2018" episode="s14e08" age="16+">Supernatural</title>
        <director>Eric Kripke</director>
        <poster>https://ae01.alicdn.com/kf/HTB1P4HDbEWF3KVjSZPhq6xclXXaF/Q2719-plakaty-i-druki-Supernatural-Season14-12x18-24x36-Sam-Dean-Winchester-Castiel-plakat-artystyczny-na-p.jpg_Q90.jpg_.webp</poster>
        <streaming-time date="13-03-2023" length="42m">17:45-18:30</streaming-time>
    </program>
    <program type="movie">
        <title year="2004" age="12+">Harry Potter and the Prisoner of Azkaban</title>
        <director>Alfonso Cuar√≥n</director>
        <poster>https://image.tmdb.org/t/p/original/aWxwnYoe8p2d2fcxOqtvAtJ72Rw.jpg</poster>
        <streaming-time date="13-03-2023" length="2h 21m">18:30-21:00</streaming-time>
    </program>
    <program type="movie">
        <title year="2009" age="12+">Avatar</title>
        <director>James Cameron</director>
        <poster>https://ae01.alicdn.com/kf/HTB1UrANLVzqK1RjSZFCq6zbxVXaK/AVATAR-film-jedwabny-plakat-malarstwo-cienne-24x36-cali.jpg</poster>
        <streaming-time date="13-03-2023" length="2h 43m">21:00-0:00</streaming-time>
    </program>
    <program type="tv-series">
        <title year="2023" episode="s01e02" age="18+">The Last of Us</title>
        <director>Craig Mazin, Neil Druckmann</director>
        <poster>https://m.media-amazon.com/images/M/MV5BZGUzYTI3M2EtZmM0Yy00NGUyLWI4ODEtN2Q3ZGJlYzhhZjU3XkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_FMjpg_UX1000_.jpg</poster>
        <streaming-time date="14-03-2023" length="53m">7:00-8:00</streaming-time>
    </program>
    <program type="animation">
        <title year="2021" age="7+">Encanto</title>
        <director>Jared Bush, Byron Howard, Charise Castro Smith</director>
        <poster>https://lumiere-a.akamaihd.net/v1/images/p_encanto_homeent_22359_4892ae1c.jpeg?region=0%2C0%2C540%2C810</poster>
        <streaming-time date="14-03-2023" length="1h 42m">8:00-9:55</streaming-time>
    </program>
    <program type="tv-series">
        <title year="2012" episode="s09e07" age="14+">The Office (US)</title>
        <director>Rodman Flender</director>
        <poster>https://m.media-amazon.com/images/I/615MPacH9qL.jpg</poster>
        <streaming-time date="14-03-2023" length="22m">9:55-10:20</streaming-time>
    </program>
    <program type="animation">
        <title year="2001" age="12+">Shrek</title>
        <director>Andrew Adamson, Vicky Jenson</director>
        <poster>https://m.media-amazon.com/images/I/513SK2F-BAL._AC_SY1000_.jpg</poster>
        <streaming-time date="14-03-2023" length="1h 30m">10:20-12:00</streaming-time>
    </program>
    <program type="movie">
        <title year="2022" age="15+">Don't Worry Darling</title>
        <director>Olivia Wilde</director>
        <poster>https://i.etsystatic.com/18242346/r/il/114afa/4210595340/il_570xN.4210595340_93op.jpg</poster>
        <streaming-time date="14-03-2023" length="2h 3m">12:00-14:15</streaming-time>
    </program>
</tvprogram>
